# Generated by Django 5.1.2 on 2024-11-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Taom turi',
                'verbose_name_plural': 'Taom turlari',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tarkibi', models.CharField(max_length=200)),
                ('narxi', models.IntegerField()),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.foodtype')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
            },
        ),
    ]
