# Generated by Django 5.1.2 on 2024-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='views',
            field=models.IntegerField(default=0, help_text='Korishlar soni'),
        ),
    ]
