# Generated by Django 5.1.2 on 2024-11-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='views',
        ),
    ]
